name: Build MA Static Dataset

on:
  push:
    branches: [ main ]
    paths:
      - "index.html"
      - "plan-viewer.css"
      - "plan-viewer.js"
      - "plan-picker.js"
      - "years/**"
      - ".github/workflows/build-ma-dataset.yml"
  workflow_dispatch: {}

# Ensure only the newest run deploys; older runs are canceled automatically
concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      # Build step (static copy). Adjust includes as needed.
      - name: Build static site
        run: |
          rm -rf dist
          mkdir -p dist
          cp -a index.html plan-viewer.css plan-viewer.js plan-picker.js years dist/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
