name: Build MA Static Dataset

on:
  push:
    branches: [ main ]
    paths:
      - "web-demo/**"
      - "years/**"
      - ".github/workflows/build-ma-dataset.yml"
  workflow_dispatch: {}

# Only keep the newest deployment run
concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Helpful logs so you can verify where files are
      - name: Show tree
        shell: bash
        run: |
          echo "pwd=$(pwd)"
          ls -la
          echo "--- web-demo ---"
          ls -la web-demo || true
          echo "--- years ---"
          ls -la years || true

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Build static site (copy web-demo → dist, add years if outside)
        shell: bash
        run: |
          set -eux
          rm -rf dist
          mkdir -p dist
          # Copy everything from the site folder
          cp -a web-demo/. dist/
          # If the dataset is at repo root, include it (no-op if already under web-demo)
          if [ -d years ] && [ ! -d dist/years ]; then
            cp -a years dist/
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
