name: Build & Deploy MA Dataset + Demo (Pages, Option A)

on:
  push:
    branches: [ main ]
    paths:
      - 'scripts/**'
      - 'web-demo/**'
      - 'data/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/build-ma-dataset.yml'
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm          # now safe because package-lock.json exists

      - name: Install deps
        run: npm ci           # requires the lock file

      - name: Build dataset (+ optional benefits)
        env:
          CMS_LANDSCAPE_URL: ${{ secrets.CMS_LANDSCAPE_URL }}
          TARGET_YEARS: ${{ secrets.TARGET_YEARS }}   # e.g. 2025
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}     # optional
        run: npm run build

      # Serve the demo and the dataset from the same site root
      - name: Copy web-demo into dist
        run: |
          mkdir -p dist/web-demo
          cp -R web-demo/* dist/web-demo/

      - name: Upload Pages artifact (dist/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
